M48
; DRILL file {KiCad 9.0.1} date 2025-04-26T09:10:30+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-26T09:10:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X123.185Y-65.18
X128.035Y-65.18
T2
X122.885Y-62.15
X128.335Y-62.15
M30
